version: "3.8"
services:
#  db:
#    container_name: "car_api_db"
#    image: mongo:latest
#    restart: always
#    volumes:
#      - ./db:/data/db:rw
#    ports:
#      - '27017:27017'
  app:
    container_name: "car_api_backend"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
#    depends_on:
#      - db
    entrypoint: ["./docker-entrypoint.sh"]